name: Pull Request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    env:
      ABI: "armeabi-v7a,arm64-v8a,x86,x86_64"
      NDK_VERSION: "25.2.9519653"
      CMAKE_VERSION: "3.22.1"
      ANDROID_PLATFORM: "23"

    steps:
      - name: Install build dependencies
        run: |
          pacman -Syu --needed --noconfirm ghc git unzip haskell-shake haskell-aeson-pretty libime opencc jdk17-openjdk python

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install NDK and CMake
        run: |
          sdkmanager --install "ndk;${{ env.NDK_VERSION }}"
          sdkmanager --install "cmake;${{ env.CMAKE_VERSION }}"

      - name: Fetch source code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build everything
        env:
          LANG: "C.UTF-8"
          ANDROID_NDK_ROOT: ${{ env.ANDROID_HOME }}/ndk/${{ env.NDK_VERSION }}
        run: |
          git config --global --add safe.directory '*'
          mkdir build && cd build
          runghc ../Main.hs -j everything

      - name: Move libraries to prebuilt and compress
        run: |
          cd build
          mkdir prebuilt
          for file in $(<artifacts.txt)
          do
            cp -a "$file" prebuilt/
          done
          tar --zstd -cf prebuilt.tar.zst prebuilt/

      - name: Upload prebuilt
        uses: actions/upload-artifact@v3
        with:
          path: build/prebuilt.tar.zst
